export default [{
    id : 0,
    title: "가장 좋은 소파",
    image: require("./assets/food1.jpg"),
    content: "18년 신축공사한 남향 원룸 ☀️, 공기청정기 제공",
    price: 340000,
    report: 0,
},
{
    id : 1,
    title: "나는 이게 제일 좋더라 옷장",
    image: require("./assets/food2.jpg"),
    content: "침실만 따로 있는 공용 셰어하우스입니다. 최대 2인 가능",
    price: 450000,
    report: 0,
},
{
    id : 2,
    title: "다 필요 없고 이 침대",
    image: require("./assets/food3.jpg"),
    content: "금산오거리 역세권 아파트입니다. 애완동물 불가능 ?",
    price: 780000,
    report: 0,
},
{
    id : 3,
    title: "라",
    image: require("./assets/food4.jpg"),
    content: "무암동인근 2인용 원룸입니다. 전세 전환가능",
    price: 550000,
    report: 0,
},
{
    id : 4,
    title: "마MyeongIl Apartment flat",
    image: require("./assets/food5.jpg"),
    content: "탄천동 아파트 월세, 남향, 역 5분거리, 허위매물아님",
    price: 680000,
    report: 0,
},
{
    id : 5,
    title: "바Banziha One Room",
    image: require("./assets/food6.jpg"),
    content: "반지하 원룸입니다. 비올 때 물가끔 새는거 빼면 좋아요",
    price: 370000,
    report: 0,
}];